version: '3.8'
services:
  backend:
    image: $DOCKERHUB_USERNAME/my-fullstack-backend:latest
    ports:
      - '3000:3000'
  frontend:
    image: $DOCKERHUB_USERNAME/my-fullstack-frontend:latest
    ports:
      - '3001:3000'
