name: Build, Push, Pull & Deploy (Self-hosted)

on:
  push:
    branches: [main]

jobs:
  build_push_pull_run:
    runs-on: self-hosted
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug secrets
        run: |
        echo "Username: $DOCKERHUB_USERNAME"
        echo "Token empty? [${DOCKERHUB_TOKEN}]"
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build backend image
        run: docker build -t binhanvku462004/my-fullstack-backend:latest ./backend

      - name: Build frontend image
        run: docker build -t binhanvku462004/my-fullstack-frontend:latest ./frontend

      - name: Login to Docker Hub
        run: echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Push backend image
        run: docker push binhanvku462004/my-fullstack-backend:latest

      - name: Push frontend image
        run: docker push binhanvku462004/my-fullstack-frontend:latest

      - name: Pull backend image
        run: docker pull binhanvku462004/my-fullstack-backend:latest

      - name: Pull frontend image
        run: docker pull binhanvku462004/my-fullstack-frontend:latest

      - name: Stop and remove old containers
        run: docker-compose down || true

      - name: Start new containers
        run: docker-compose up -d

      - name: Clean up old images
        run: docker image prune -f
